namespace: vector-test-kustomize

bases:
  - github.com/timberio/vector/distribution/kubernetes?ref=k8s-kubectl-deployment

images:
  - name: timberio/vector
    newName: mozgiii/vector-k8s-wip
    newTag: rev7

resources:
  - namespace.yaml

configMapGenerator:
  - name: vector-config
    files:
      - configs/vector.toml

generatorOptions:
  disableNameSuffixHash: true
