# Configure vector-agent to send the logs from the built-in `kubernetes_logs`
# source to the stdout.
vector-agent:
  sinks:
    stdout:
      type: console
      inputs: ["kubernetes_logs"]
      rawConfig: |
        target = "stdout"
        encoding = "json"
